export default (app) => {
  app.post(
    `/tenant/:tenantId/anno-formazione-scuola-lavoro`,
    require('./annoFormazioneScuolaLavoroCreate').default,
  );
  app.put(
    `/tenant/:tenantId/anno-formazione-scuola-lavoro/:id`,
    require('./annoFormazioneScuolaLavoroUpdate').default,
  );
  app.post(
    `/tenant/:tenantId/anno-formazione-scuola-lavoro/import`,
    require('./annoFormazioneScuolaLavoroImport').default,
  );
  app.delete(
    `/tenant/:tenantId/anno-formazione-scuola-lavoro`,
    require('./annoFormazioneScuolaLavoroDestroy').default,
  );
  app.get(
    `/tenant/:tenantId/anno-formazione-scuola-lavoro/autocomplete`,
    require('./annoFormazioneScuolaLavoroAutocomplete').default,
  );
  app.get(
    `/tenant/:tenantId/anno-formazione-scuola-lavoro`,
    require('./annoFormazioneScuolaLavoroList').default,
  );
  app.get(
    `/tenant/:tenantId/anno-formazione-scuola-lavoro/:id`,
    require('./annoFormazioneScuolaLavoroFind').default,
  );
};
