export default (app) => {
  app.post(
    `/tenant/:tenantId/ciclo-monte-ore`,
    require('./cicloMonteOreCreate').default,
  );
  app.put(
    `/tenant/:tenantId/ciclo-monte-ore/:id`,
    require('./cicloMonteOreUpdate').default,
  );
  app.post(
    `/tenant/:tenantId/ciclo-monte-ore/import`,
    require('./cicloMonteOreImport').default,
  );
  app.delete(
    `/tenant/:tenantId/ciclo-monte-ore`,
    require('./cicloMonteOreDestroy').default,
  );
  app.get(
    `/tenant/:tenantId/ciclo-monte-ore/autocomplete`,
    require('./cicloMonteOreAutocomplete').default,
  );
  app.get(
    `/tenant/:tenantId/ciclo-monte-ore`,
    require('./cicloMonteOreList').default,
  );
  app.get(
    `/tenant/:tenantId/ciclo-monte-ore/:id`,
    require('./cicloMonteOreFind').default,
  );
};
