export default (app) => {
  app.post(
    `/tenant/:tenantId/corso`,
    require('./corsoCreate').default,
  );
  app.put(
    `/tenant/:tenantId/corso/:id`,
    require('./corsoUpdate').default,
  );
  app.post(
    `/tenant/:tenantId/corso/import`,
    require('./corsoImport').default,
  );
  app.delete(
    `/tenant/:tenantId/corso`,
    require('./corsoDestroy').default,
  );
  app.get(
    `/tenant/:tenantId/corso/autocomplete`,
    require('./corsoAutocomplete').default,
  );
  app.get(
    `/tenant/:tenantId/corso`,
    require('./corsoList').default,
  );
  app.get(
    `/tenant/:tenantId/corso/:id`,
    require('./corsoFind').default,
  );
};
